server:
    port: 6060

spring:
    application:
        name: user-service

    datasource:
        uri:    jdbc:h2:mem:userdb
        driverClassName:    org.h2.Driver
        username:   sa
        password:
    jpa:
        database-platform:  org.hibernate.dialect.H2Dialect
        show-sql:   true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled:    true
            path:   /h2-console

eureka:
    client:
        service-url:
            defaultZone:    http://localhost:6069/eureka/

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        com.imart.user.userService: DEBUG