server:
    port: 6063

spring:
    application:
        name: order-application

#database configuration
    datasource:
        uri: jdbc:h2:mem:orderdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console

#kafka configuration
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            retries: 5
            acks: all
            properties:
                spring.json.add.type.headers: false
        consumer:
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            enable-auto-commit: true
            auto-offset-reset: earliest
            properties:
                spring.deserializer.support.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: "*"

#kafka topic declaration
app:
    kafka:
        topics:
            producer:
                order-initiated-topic: "sales.orders.v1.initiated"
                order-created-topic: "sales.orders.v1.created"
            consumer:
                checkout-topic: "sales.checkout.v1.initiated"
                payment-successful-topic: "sales.payment.v1.success"
    service:
        redirection:
            url:
                address-resolution-service: http://localhost:6063/api/v1/checkout/address
                payment-processing-service: http://localhost:6063/api/v1/checkout/payment
                cart-validation-service: http://localhost:6063/api/v1/checkout/carts/validate
# redis configuration for custom and turbo
custom:
    redis:
        vault:
            host: localhost
            port: 7070
        turbo:
            host: localhost
            port: 7071


logging:
    level:
        root: INFO
        org.springframework.amqp:   DEBUG

eureka:
    client:
        service-url:
            defaultZone: http://localhost:6069/eureka/
            register-with-eureka:   true
            fetch-registry: true
