server:
    port: 6062

spring:
    application:
        name: cart-service

# database config
    datasource:
        url: jdbc:h2:mem:cartdb
        driverClassName: org.h2.Driver
        password:
        username: sa
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    format_sql: true

 #h2 custom config
    h2:
        console:
            enabled: true
            path: /h2-console

#eureka client config
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:6069/eureka/
            register-with-eureka: true
            fetch-registry: true
#spring kafka config
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            retries: 5
            acks: all
            properties:
                spring.json.add.type.headers: false
        consumer:
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            enable-auto-commit: true
            auto-offset-reset: earliest
            properties:
                spring.deserializer.support.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: "*"

#application kafka config
app:
    kafka:
        topics:
            producer:
                checkout-event: "sales.checkout.v1.initiated"
            consumer:
                order-created-event: "sales.orders.v1.created"
    service:
        redirection:
            url:
                checkout-service-url: http://localhost:6063/api/v1/checkout/init
#actuator configs
management:
    endpoints:
        web:
            exposure:
                include: "*"
        tracing:
            sampling:
                probability: 1.0

#console logging
logging:
    level:
        root: INFO
        com.imart.cart.cart-service: DEBUG
