spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
            https://github.com/foxx-7/private-config-repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:6069/eureka
    register-with-eureka: true
    fetch-registry: true


  server:
    port:
      6068
